version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  redis:
    image: redis:alpine
    # ports:
    #   - "${VFAIR_REDIS_PORT}:6379"
    networks:
      - backend
  
  postgres:
    build:
      context: ./postgresql
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      #- ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
        - "${POSTGRES_PORT}:5432"
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
        - backend
   
  caddy:
    build:
      context: ./caddy
    volumes:
      - ${CADDY_FILE}:/etc/Caddyfile
      - ${APP_CODE_PATH_HOST}/ssl:/var/www/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "2015:2015"
    networks:
      - frontend


  node1_api:
    build:
      context: ./nodejs
      args:
        - GIT_ADDRESS=${GIT_COMMON_LOGIC}
        - GIT_KEY=${GIT_KEY}        
    # ports: 
    #   - "3001:${NODE1_API_SRV_SERVICE_PORT}"
    networks:
      - frontend
      - backend
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_HOST}
      - NODE1_API_SRV_SERVICE_HOST=node1_api
      - NODE1_API_SRV_SERVICE_PORT=3001
      - NODE2_API_SRV_SERVICE_HOST=node2_api
      - NODE2_API_SRV_SERVICE_PORT=3002
      - NODE1_SERVICE_SRV_SERVICE_HOST=node1_service
      - NODE1_SERVICE_SRV_SERVICE_PORT=4001

  node2_api:
    build:
      context: ./nodejs
      args:
        - GIT_ADDRESS=${GIT_COMMON_LOGIC}
        - GIT_KEY=${GIT_KEY}        
    # ports: 
    #   - "3002:${NODE2_API_SRV_SERVICE_PORT}"
    networks:
      - frontend
      - backend
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_HOST}
      - NODE1_API_SRV_SERVICE_HOST=node1_api
      - NODE1_API_SRV_SERVICE_PORT=3001
      - NODE2_API_SRV_SERVICE_HOST=node2_api
      - NODE2_API_SRV_SERVICE_PORT=3002
      - NODE1_SERVICE_SRV_SERVICE_HOST=node1_service
      - NODE1_SERVICE_SRV_SERVICE_PORT=4001

  node1_service:
    build:
      context: ./nodejs
      args:
        - GIT_ADDRESS=${GIT_COMMON_LOGIC}
        - GIT_KEY=${GIT_KEY}        
    # ports: 
    #   - "4001:${NODE1_SERVICE_SRV_SERVICE_PORT}"
    networks:
      - frontend
      - backend
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_HOST}
      - NODE1_API_SRV_SERVICE_HOST=node1_api
      - NODE1_API_SRV_SERVICE_PORT=3001
      - NODE2_API_SRV_SERVICE_HOST=node2_api
      - NODE2_API_SRV_SERVICE_PORT=3002
      - NODE1_SERVICE_SRV_SERVICE_HOST=node1_service
      - NODE1_SERVICE_SRV_SERVICE_PORT=4001